#!/bin/bash
#
# initd a node app
# Based on a script posted by https://gist.github.com/jinze at https://gist.github.com/3748766
#

# Source function library.
. /lib/lsb/init-functions

pidFile=/var/run/flo.pid
logFile=/var/www/flo.log

nodeApp=flo.js

start() {
   echo "Starting $nodeApp"
   cd /var/www/
   sudo forever start --pidFile $pidFile -l $logFile -a -d $nodeApp
   RETVAL=$?
}

restart() {
	echo -n "Restarting $nodeApp"
	sudo forever restart $nodeApp
	RETVAL=$?
}

stop() {
   echo -n "Shutting down $nodeApp"
   sudo forever stop $nodeApp
   RETVAL=$?
}

status() {
   echo -n "Status $nodeApp"
   sudo forever list
   RETVAL=$?
}

case "$1" in
   start)
        start
        ;;
    stop)
        stop
        ;;
   status)
        status
       ;;
   restart)
   	restart
        ;;
	*)
       echo "Usage:  {start|stop|status|restart}"
       exit 1
        ;;
esac
exit $RETVAL
